### ISSUE TITLE
Run the grid-search with a dynamical model

### ISSUE THREAD

**Issue by miguelgondu** [juanrloaiza/latinamerican-philosophy-mining#16]
- [x] Confirm whether we can easily compute the metrics (coherence, log-perplexity and so on) using Blei's binary.
    - [x] If we use it, do we need to re-implement coherence and log-perplexity?
- [x] Re-implement the grid search using these metrics (or the ones from the seq. model).

**Comment by juanrloaiza** [comment]
Both `gensim.models.LdaSeq` and `gensim.models.wrappers.dtmmodel` implement [this function](https://github.com/RaRe-Technologies/gensim/blob/e889fa3d45a406cabbc7e180fa9a8ee3f76ac6f0/gensim/models/ldaseqmodel.py#L629-L652) for `dtm_coherence`. Seems that this is the input for `gensim.models.coherencemodel` and it seems easy to implement for the files we have. We should implement this function for our "wrapper" and test this.

**Comment by juanrloaiza** [comment]
We can compute model coherence using the same procedure mentioned above. This means we can use `gensim.models.coherencemodel` to compute this metric. However, we can only compute it for one time slice or for the averaged model. We should briefly check which alternative is better from a conceptual standpoint.

**Comment by miguelgondu** [comment]
- We can think about computing the mean coherence if computing the coherence per slice is not expensive.
- We can drop log-perplexity, just for convenience sake.

**Comment by miguelgondu** [comment]
@juanrloaiza did it, the legend.
