### ISSUE TITLE
Freeze the models, and pick a final one.

### ISSUE THREAD

**Issue by miguelgondu** [juanrloaiza/latinamerican-philosophy-mining#17]
- [x] Freeze the corpus (make sure that all the articles are in Spanish).
- [x] Re-run the experiments (the grid-search). Confirm whether 90 topics is ideal. (See Issue #16)
- [x] Choose the final model after re-running the grid search.

**Comment by miguelgondu** [comment]
- [x] Visualize not only 50% mass, but also at least 10 words.
- [x] Run a couple more models (maybe 6) on 90 topics.
- [x] Choose a final model.

**Comment by juanrloaiza** [comment]
We decided on `seed=36775`.
