### ISSUE TITLE
Better optimization?

### ISSUE THREAD

**Issue by miguelgondu** [juanrloaiza/latinamerican-philosophy-mining#18]
Some of the topics are not converging. Should we change the training hyperparameters?

**Comment by miguelgondu** [comment]
We used to have great models at `n_topics=90`.

- [x] Train 60, 90 using the cleaner corpus

**Comment by juanrloaiza** [comment]
We decided that `n=90` gave the best models. Closing.

**Comment by miguelgondu** [comment]
90 seems to be a sweet spot. Weird. We could analyse the optimization landscape in the future.
