### ISSUE TITLE
Decide on which DTM model to use, if any

### ISSUE THREAD

**Issue by miguelgondu** [juanrloaiza/latinamerican-philosophy-mining#19]
We are not happy with the new results from either Blei's binary, Gensim, or Tomotopy's. Which one should we use? There might be other tools in other languages (R, Cpp...)

One example: https://github.com/Arnie0426/FastDTM

**Comment by miguelgondu** [comment]
- [ ] Let the Tomotopy train for looooong.
- [ ] Train a 90 topic in the Blei binary.
- [ ] Take a look at [FastDTM](https://github.com/Arnie0426/FastDTM)
- [ ] Move to another compiled model/language.
- [ ] Drop DTMs.

**Comment by juanrloaiza** [comment]
We finally decided to use Blei's binary.
