### ISSUE TITLE
Set a criteria for garbage topics

### ISSUE THREAD

**Issue by miguelgondu** [juanrloaiza/latinamerican-philosophy-mining#22]
We need to select a set of criteria (as basic as possible) for a topic to be garbage. Some of them:is e.g.

- having 0.5 probability mass in >2000 words.
- having 0.5 probability mass in >200 documents.
- having more than 0.75 probability mass in a single word.

- [x] Implement this.

**Comment by miguelgondu** [comment]
Solved in previous commits.

**Comment by juanrloaiza** [comment]
Topic 78 has only one word ("múltiple") accounting for 0.5 of the probability mass. The second word is "reflexiones", and afterwards it seems to follow a garbage-topic-like list of words in alphabetical order:

- corrupción
- cosmo
- cosmología
- criatura
- cualitativo
- curiosidad
- célebre
- data

Perhaps we should be more strict with the words for 0.75 probability mass criterion?

**Comment by juanrloaiza** [comment]
Criteria were functioning. We should only check the markdown output.
